# -*- coding: utf-8 -*-
"""Exercicio_modulo_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUOGk4gi1VuA4UQvuJXw1IfNnP869udx
"""

num1 = float(input("Digite o primeiro número que deseja calcular: "))
num2 = float(input("Digite o segundo número que deseja calcular: "))

print("Escolha agora qual tipo de operação deseja realizar: ")
print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")

operacao = input("Escolha o número de 1 a 4 para a operação que deseja realizar: ")
if operacao == "1":
  resultado = num1 + num2
  print(f"\n{num1} + {num2} = {resultado}")
elif operacao == "2":
  resultado = num1 - num2
  print(f"\n{num1} - {num2} = {resultado}")
elif operacao == "3":
  resultado = num1 * num2
  print(f"\n{num1} * {num2} = {resultado}")
elif operacao == "4":
  if num1 == 0 or num2 == 0:
    print("Não é possivel fazer divisão com 0!")
  else:
    resultado = num1 / num2
    print(f"\n{num1} / {num2} = {resultado}")
else:
  print("Operação invalida, por favor selecione a operação de 1 a 4!")